version: '3.9'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    shm_size: '4gb'
    container_name: pets-db
    restart: 'unless-stopped'
    environment:
      - SA_PASSWORD=Owns32159!
      - ACCEPT_EULA=Y
    ports:
      - '1122:1433'
    volumes:
      - Db:/var/opt/mssql/data

volumes:
  Db:
    driver: local